language: generic

cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.composer/cache
    - $HOME/public

jobs:
  include:
    - stage: build
      skip: true
      node_js: '10.16'
      script: yarn install && yarn production
      after_success: cp $TRAVIS_BUILD_DIR/public $HOME/public
#    - stage: test
#      node_js: '10.16'
#      script: yarn test
#    - stage: test
#      php: '7.2'
#      script:
#        - composer install --no-dev
#        - composer test
    - stage: deploy
      php: '7.2'
#      script: php artisan deploy -s upload
      script:
        - composer install --no-dev
        - php artisan inspire
