language: generic

cache:
  directories:
    - $HOME/.cache/yarn
    - $HOME/.composer/cache
    - $HOME/public

jobs:
  include:
    - stage: build
      skip: true
      node_js: '10.16'
      script:
        - yarn install
        - yarn production
        - cp -r $TRAVIS_BUILD_DIR/public $HOME
#    - stage: test
#      node_js: '10.16'
#      script: yarn test
#    - stage: test
#      php: '7.2'
#      script:
#        - composer install --no-dev
#        - composer test
    - stage: deploy
      php: '7.2'
      before_script: echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
      script:
        - composer install
        - cp -r $HOME/public $TRAVIS_BUILD_DIR
        - php artisan nova:publish
        - php artisan deploy -s upload
