version: '3.8'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: jorgeglz
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"
