name: CI/CD

on:
  - push
  - pull_request

jobs:
  php-ci:
    name: PHP CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Composer Install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: PHP-CS-Fixer Test
        run: composer test:lint
  node-ci:
    name: NodeJS CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Yarn Install
        run: yarn install -s --ignore-scripts --non-interactive --no-progress --frozen-lockfile
      - name: ESLint Test
        run: yarn lint
